const OUT_FOR_DELIVERY_SHIPMENT_CODE = "6.0";
const OUT_FOR_DELIVERY_SHIPMENT_STATUS_CODE = 'out_for_delivery';
const OUT_FOR_DELIVERY_SHIPMENT_STATUS_MESSAGE = 'Out for delivery';

const RTO_DELIVERED_SHIPMENT_CODE = "7.1";
const RTO_DELIVERED_SHIPMENT_STATUS_CODE = 'rto_delivered';
const RTO_DELIVERED_SHIPMENT_STATUS_MESSAGE = 'RTO Delivered';

const DELIVERED_SHIPMENT_CODE = "7.0";
const DELIVERED_SHIPMENT_STATUS_CODE = 'delivered';
const DELIVERED_SHIPMENT_STATUS_MESSAGE = 'Delivered';

const REFUNDED_SHIPMENT_CODE = "10.0";
const REFUNDED_SHIPMENT_STATUS_CODE = 'refunded';
const REFUNDED_SHIPMENT_STATUS_MESSAGE = 'Refunded';

const RTO_INITIATED_SHIPMENT_CODE = "7.0";
const RTO_INITIATED_SHIPMENT_STATUS_CODE = 'rto_initiated';
const RTO_INITIATED_SHIPMENT_STATUS_MESSAGE = 'RTO Initiated';

const PICKED_UP_SHIPMENT_CODE = "8.0";
const PICKED_UP_SHIPMENT_STATUS_CODE = 'picked_up';
const PICKED_UP_SHIPMENT_STATUS_MESSAGE = 'Picked up';

const RECEIVED_AT_WAREHOUSE_SHIPMENT_CODE = "9.0";
const RECEIVED_AT_WAREHOUSE_SHIPMENT_STATUS_CODE = 'received_at_warehouse';
const RECEIVED_AT_WAREHOUSE_SHIPMENT_STATUS_MESSAGE = 'Received at warehouse';

module.exports = {
  OUT_FOR_DELIVERY_SHIPMENT_CODE,
  OUT_FOR_DELIVERY_SHIPMENT_STATUS_CODE,
  OUT_FOR_DELIVERY_SHIPMENT_STATUS_MESSAGE,
  RTO_DELIVERED_SHIPMENT_CODE,
  RTO_DELIVERED_SHIPMENT_STATUS_CODE,
  RTO_DELIVERED_SHIPMENT_STATUS_MESSAGE,
  DELIVERED_SHIPMENT_CODE,
  DELIVERED_SHIPMENT_STATUS_CODE,
  DELIVERED_SHIPMENT_STATUS_MESSAGE,
  REFUNDED_SHIPMENT_CODE,
  REFUNDED_SHIPMENT_STATUS_CODE,
  REFUNDED_SHIPMENT_STATUS_MESSAGE,
  RTO_INITIATED_SHIPMENT_CODE,
  RTO_INITIATED_SHIPMENT_STATUS_CODE,
  RTO_INITIATED_SHIPMENT_STATUS_MESSAGE,
  PICKED_UP_SHIPMENT_CODE,
  PICKED_UP_SHIPMENT_STATUS_CODE,
  PICKED_UP_SHIPMENT_STATUS_MESSAGE,
  RECEIVED_AT_WAREHOUSE_SHIPMENT_CODE,
  RECEIVED_AT_WAREHOUSE_SHIPMENT_STATUS_CODE,
  RECEIVED_AT_WAREHOUSE_SHIPMENT_STATUS_MESSAGE
};
