sonar.projectKey=Styli-dev_OMS-Service
sonar.organization=styli-dev
# relative paths to source directories. More details and properties are described
# in https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/
sonar.sources=src,config,migrations
# Exclude node_modules, test, coverage, and other non-source to avoid bridge timeout and irrelevant analysis
sonar.exclusions=**/node_modules/**,**/test/**,**/coverage/**,**/*.min.js,**/docs/**,**/.github/**,**/.helm/**,**/.owasp/**
