#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()

if branch.startswith('feature/') or branch.startswith('hotfix/') or branch.startswith('bugfix/'):

    with open(commit_msg_filepath, 'r') as f:
        content = f.read()
        result = re.match('([A-Z]{1,4}-(.*\s))([A-Za-z0-9 ]{15,200})', content)
        if (result is None):
            print "Commit message should starts with Jira Issue Number and description must be greater than 15 char. Eg: CUR-123 This is a commit message having more than 15 charactors "
            sys.exit(1)
        issue_number = result.group(0)
        issue_description = result.group(1)
        # required_message = "ISSUE-%s" % issue_number
        # if not content.startswith(required_message):
        #     print "commit-msg: ERROR! The commit message must start with '%s'" % required_message
        #     sys.exit(1)
else :
    print "Your branch should be either of the following: feature/ bugfix/ hotfix/"
    sys.exit(1)
