exports.permissionMap = {
  '/v1/orders/list': { ability: 'order', action: 'read' },
  '/v1/store/list': { ability: 'store', action: 'read' },
  '/v1/store/update-store': { ability: 'store', action: 'update' },
  '/v1/store/website-list': { ability: 'store', action: 'read' },
  '/v1/store/create-store': { ability: 'store', action: 'create' },
  '/v1/store/create-website': { ability: 'store', action: 'create' },
  '/v1/store/detail': { ability: 'store', action: 'read' },
  '/v1/store/warehouse-location-list': { ability: 'store', action: 'read' },
  '/v1/orders/detail': {
    ability: 'order',
    action: 'read',
    message: 'User not allowed to read orders!'
  },
  '/v1/orders/invoice': { ability: 'invoice', action: 'read' },
  '/v1/orders/shipment': { ability: 'shipment', action: 'read' },
  '/v1/orders/creditmemo': { ability: 'creditmemo', action: 'read' },
  '/v1/orders/creditmemo/update': { ability: 'order', action: 'update' },
  '/v1/orders/quote/get': { ability: 'order', action: 'create' },
  '/v1/orders/quote/setPayment': { ability: 'order', action: 'create' },
  '/v1/orders/quote/coupon': { ability: 'order', action: 'create' },
  '/v1/orders/quote/removeproduct': { ability: 'order', action: 'delete' },
  '/v1/orders/quote/setAddress': { ability: 'order', action: 'update' },
  '/v1/orders/createOrder': { ability: 'order', action: 'create' },
  '/v1/orders/recreateOrder': { ability: 'order', action: 'create' },
  '/v1/orders/address': { ability: 'order', action: 'update' },
  '/v1/orders/status': { ability: 'order', action: 'update' },
  '/v1/orders/create-shipment': { ability: 'order', action: 'update' },
  '/v1/orders/create-awb': { ability: 'order', action: 'update' },
  '/v1/orders/order-status-list': { ability: 'order', action: 'read' },
  '/v1/orders/update/order-status-details': {
    ability: 'order',
    action: 'update'
  },
  ':inventory/:sku': { ability: 'inventory', action: 'read' },
  '/v1/logging/adminlogs': { ability: 'logs', action: 'read' },
  '/detail/:customerId': { ability: 'customer', action: 'read' },
  '/address/list/:customerId': { ability: 'customer', action: 'read' },
  '/addressMap/:countryLocale': { ability: 'customer', action: 'read' },
  '/v1/orders/jwt': { ability: 'order', action: 'create' },
  '/v1/orders/braze-log-custom-event': { ability: 'order', action: 'read' },
  '/v1/orders/autoRefundList': { ability: 'rtoAutoRefund', action: 'read' },
  '/v1/orders/statusUpdate': { ability: 'order', action: 'update' },
  '/consul/:type': { ability: 'config', action: 'read' },
  '/v1/config/consul/save': { ability: 'config', action: 'create' },
  '/v1/customers/list': { ability: 'customer', action: 'read' },
  '/v1/customer/addressMap/:countryLocale': {
    ability: 'customer',
    action: 'update'
  },
  '/v1/customer/update': { ability: 'customer', action: 'update' },
  '/v1/customer/address/list/:customerId': {
    ability: 'customer',
    action: 'read'
  },
  '/v1/dashboard/orderDashboard': { ability: 'dashboard', action: 'read' },
  '/v1/dashboard/orderSalesChartDashboard': {
    ability: 'dashboard',
    action: 'read'
  },

  '/v1/customer/wallet/list': { ability: 'customer', action: 'read' },
  '/v1/customer/wallet/add': { ability: 'wallet', action: 'create' },
  '/v1/dashboard/orderStats': { ability: 'dashboard', action: 'create' },
  '/v1/dashboard/bestsellerStats': { ability: 'dashboard', action: 'read' },
  '/v1/rma/detail': { ability: 'rma', action: 'read' },
  '/v1/rma/update': { ability: 'rma', action: 'update' },
  '/v1/rma/init': {
    ability: 'rma',
    action: 'update'
  },
  '/v1/rma/rma-status-list': { ability: 'rma', action: 'read' },
  '/v1/rma/create': { ability: 'rma', action: 'create' },
  '/v1/rma/list': { ability: 'rma', action: 'read' },
  '/v1/rma/remove/tracking': { ability: 'rma', action: 'delete' },
  '/v1//update/rma-status-details': { ability: 'rma', action: 'update' },
  '/create/tracking/:requestId': { ability: 'rma', action: 'create' },
  '/v1/rma/recreate': { ability: 'rma', action: 'create' },
  '/v1/rma/return-reason-list': { ability: 'rma', action: 'read' },
  '/v1/rma/cancel-reason-list': { ability: 'cancelReason', action: 'read' },
  '/v1/roles/groups': { ability: 'role', action: 'read' },
  '/v1/roles/group': { ability: 'role', action: 'create' },
  '/group/:id': { ability: 'role', action: 'delete' },
  '/v1/roles/teams': { ability: 'role', action: 'read' },
  '/v1/roles/team': { ability: 'role', action: 'create' },
  '/v1/roles/users': { ability: 'user', action: 'read' },
  '/v1/roles/user': { ability: 'user', action: 'create' },
  '/user/:id': { ability: 'user', action: 'delete' },
  // '/v1/users/manageUsers': { ability: 'user', action: 'create' },
  // '/v1/users/getUsers': { ability: 'user', action: 'read' },
  // '/:userId': { ability: 'user', action: 'read' },
  '/v1/banktransfer/list': { ability: 'transfer', action: 'read' },
  '/v1/banktransfer/create': { ability: 'transfer', action: 'create' },
  '/v1/banktransfer/upload/list': { ability: 'transfer', action: 'read' },
  '/v1/banktransfer/process': {
    ability: 'transfer',
    action: 'update'
  },
  '/v1/rest/fetch-uploads': { ability: 'returnAWB', action: 'read' },
  '/v1/customers/address/update': { ability: 'customer', action: 'update' },
  '/v1/customers/wallet/list': { ability: 'customer', action: 'read' },
  '/v1/customers/wallet/add': { ability: 'customer', action: 'update' },
  '/v1/orders/check-inventory': { ability: 'order', action: 'create' },
  '/rma-status-details/:statusId': { ability: 'rma', action: 'read' },
  '/team/:id': { ability: 'role', action: 'delete' },
  '/V1/sms/fetchSMSList': { ability: 'sms', action: 'read' },
  '/order-status-details/:statusCode': { ability: 'order', action: 'read' },
  '/v1/customers/update': { ability: 'customer', action: 'update' },
  '/v1/misc/gerPermissionTargets': { ability: 'role', action: 'create' },
  '/v1/rest/upload-file': { ability: 'inventoryAdmin', action: 'update' },
  '/v1/misc/download/file': { ability: 'download', action: 'read' },
  '/v1/orders/generate/invoice/list': {
    ability: 'bulkInvoice',
    action: 'read'
  },
  '/v1/orders/generate/invoice': { ability: 'bulkInvoice', action: 'create' },
  '/v1/earn/list': { ability: 'earn', action: 'read' }
};
