exports.INVALID_CREDIT_CARD = 16;
exports.INVALID_CARD_EXPIRED = 12;
exports.INVALID_PAYMENT_OPTION = 14;
exports.PAYMENT_OPTION_DISABLED = 3;
exports.INVALID_EXPIRY_DATE = 100;

exports.FAILURE = 'FAILURE';
exports.SUCCESS = 'SUCCESS';
