const SimpleSchema = require("simpl-schema");

const metadataObject = new SimpleSchema({
    "categoryId": { type: String, optional: true },
    "categoryName": { type: String, optional: true },
    "path": { type: String, optional: true },
})

exports.QuoteSchema = new SimpleSchema({
    "id": { type: String },
    "storeId": { type: Number },
    "source": { type: Number, optional: true },
    "customerId": { type: String, optional: true },
    "customerEmail": { type: String, optional: true },
    "customerFirstname": { type: String, optional: true },
    "customerLastname": { type: String, optional: true },
    "customerDob": { type: String, optional: true },
    "customerIsGuest": { type: Number },
    "quoteItem": { type: Array, optional: true },
    "quoteItem.$": new SimpleSchema({
        "parentProductId": { type: String, optional: true },
        "productId": { type: String, optional: true },
        "storeId": { type: Number, optional: true },
        "parentSku": { type: String },
        "sku": { type: String },
        "name": { type: String },
        "qty": { type: Number },
        "price": { type: Number, optional: true },
        "basePrice": { type: Number, optional: true },
        "discountPercent": { type: Number, optional: true },
        "discountAmount": { type: Number, optional: true },
        "baseDiscountAmount": { type: Number, optional: true },
        "taxPercent": { type: Number, optional: true },
        "taxAmount": { type: Number, optional: true },
        "baseTaxAmount": { type: Number, optional: true },
        "rowTotal": { type: Number, optional: true },
        "baseRowTotal": { type: Number, optional: true },
        "rowTotalWithDiscount": { type: Number, optional: true },
        "productType": { type: String, optional: true },
        "priceInclTax": { type: Number, optional: true },
        "basePriceInclTax": { type: Number, optional: true },
        "rowTotalInclTax": { type: Number, optional: true },
        "baseRowTotalInclTax": { type: Number, optional: true },
        "discountTaxCompensationAmount": { type: Number, optional: true },
        "baseDiscountTaxCompensationAmount": { type: Number, optional: true },
        "superAttributeId": { type: String, optional: true },
        "superAttributeValue": { type: String, optional: true },
        "superAttributeLabel": { type: String, optional: true },
    }),
    "convertedAt": { type: Date, optional: true },
    "isActive": { type: Number },
    "itemsCount": { type: Number },
    "itemsQty": { type: Number },
    "storeToBaseRate": { type: Number, optional: true },
    "baseCurrencyCode": { type: String },
    "storeCurrencyCode": { type: String },
    "grandTotal": { type: Number, optional: true },
    "baseGrandTotal": { type: Number, optional: true },
    "appliedRuleIds": { type: Array, optional: true },
    "appliedRuleIds.$": Number,
    "couponCode": { type: String, optional: true },
    "subtotal": { type: Number, optional: true },
    "baseSubtotal": { type: Number, optional: true },
    "subtotalWithDiscount": { type: Number, optional: true },
    "baseSubtotalWithDiscount": { type: Number, optional: true },
    "triggerRecollect": { type: Number, optional: true },
    "amstorecreditUse": { type: Number, optional: true },
    "amstorecreditBaseAmount": { type: Number, optional: true },
    "amstorecreditAmount": { type: Number, optional: true },
    "promoAppliedAt": { type: Date, optional: true },
    "quoteAddress": { type: Array, optional: true },
    "quoteAddress.$": new SimpleSchema({
        "customerAddressId": { type: SimpleSchema.oneOf(String, Number), optional: true },
        "addressType": { type: String },
        "email": { type: String, optional: true },
        "firstname": { type: String, optional: true },
        "lastname": { type: String, optional: true },
        "street": { type: String, optional: true },
        "city": { type: String, optional: true },
        "region": { type: String, optional: true },
        "regionId": { type: String, optional: true },
        "postcode": { type: String, optional: true },
        "countryId": { type: String, optional: true },
        "telephone": { type: SimpleSchema.oneOf(String, Number), optional: true },
        "shippingMethod": { type: String, optional: true },
        "shippingDescription": { type: String, optional: true },
        "locationType": { type: String, optional: true },
        "nearestLandmark": { type: String, optional: true },
        "area": { type: String, optional: true },
        "buildingNumber": { type: SimpleSchema.oneOf(String, Number), optional: true },
        "unitNumber": { type: String, optional: true },
        "postalCode": { type: String, optional: true },
        "shortAddress": { type: String, optional: true },
        "nationalId": { type: Object, optional: true },
    }),
    "quotePayment": new SimpleSchema({
        "method": { type: String, optional: true },
        "additionalInformation": { type: String, optional: true },
        "createdAt": { type: Date, optional: true },
        "updatedAt": { type: Date, optional: true },
    }),
    "metadata": { type: Array, optional: true },
    "metadata.$": new SimpleSchema({
        "level-1": { type: Array, optional: true },
        "level-1.$": metadataObject,
        "level-2": { type: Array, optional: true },
        "level-2.$": metadataObject,
        "level-3": { type: Array, optional: true },
        "level-3.$": metadataObject,
        "level-4": { type: Array, optional: true },
        "level-4.$": metadataObject,
        "sku": { type: String, optional: true },
        "productId": { type: String, optional: true },
    })
});
