omsnode:
  domain: oms-api-qa.stylishop.store
  node_env: qa
  replicaCount: 1
  apmkey: 4d45uzw9n5208tX9aYBtJ1Zz
  appname: omsnode
  mongo_auth_dev: oms_qa
  mongo_url: mongodb://10.128.0.55:27017,10.128.0.56:27017,10.128.0.57:27017
  mongo_db: oms_qa
  mongo_user: oms_qa
  mongo_pass: vehvb763bf387fgb
  mongo_node_count: 3
  gcp_project_id: stylishopdev
  gs_bucket_name: oms_styli_dev
  consul_host: consul-consul-consul-server.consul
  consul_port: 8500
  consul_credentials_env: credentials_qa
  consul_app_config_env: appConfig_qa
  oms_api_host: https://oms-api-qa.stylishop.store
  archive_mysql_host: 35.209.78.189
  archive_mysql_user: oms_qa
  archive_mysql_pwd: Jd3b36fvd3guve87
  archive_mysql_db: oms_archive_qa
  archive_mysql_port: 3306
  java_order_base_url: http://order-service-oms.oms-qa
  java_customer_base_url: http://customer-service.customer-qa
  quote_base_url: http://quote-service.quote-qa
  python_base_url: http://facto.stylishop.store
  bucket_base_url: https://dev-bucket.stylifashion.com/qa
  elastic_apm_service_name: oms-qa-node-service
  elastic_apm_service_token:
  elastic_apm_service_url: https://10.128.0.50:8200
  kafka_groupid: oms-service-logging-qa
  kafka_inventory_groupid: inventory-logging-qa
  kafka_clientid: oms-service-consumer-qa
  kafka_brokerlist: 34.72.148.227:9092
  kafka_v2_brokerlist: 34.72.148.227:9092
  kafka_order_success_topic: order-sms-topic_qa
  kafka_inventory_logging_topic: inventory_logging_qa
  kafka_auto_refund_topic: queue_based_refund_dropoff
  kafka_shipment_update_topic: shipment_update_navik_qa
  mysql_host: 10.128.0.20
  mysql_user: oms_uat
  mysql_pwd: Vehufb38fbhjfe84
  mysql_db: oms_uat
  mysql_port: 3306
  mulin_url:  http://mulin.mulin-qa:8080
  braze_base_url: https://rest.fra-01.braze.eu
  braze_auth_token: 647b102f-8c5e-479a-af02-1b9fa83dd3d9
  inventory_base_url: http://inventory.oms-qa:8080
  eas_url: https://qa-eas.stylifashion.com
  custmgmt_base_url: http://customermg.customer-qa:5003
  memorylim: 1000Mi
  cpulim: 1000m
  memoryreq: 1000Mi
  cpureq: 1000m
  authservice_base_url: https://dev-sentinel-api.stylifashion.com/api/v1/auth
  fresh_chat_whatsapp: https://api.freshchat.com/v2/outbound-messages/whatsapp
  servicekeyname: oms-qa
  city_data_api_url: http://adrsmpr.adrsmpr-qa:8080
  main_website_host_name: https://qa.stylifashion.com
  kafka_shipment_return_update_topic: return_shipment_update_navik_qa
  return_invoice_bucket_url: navik-sandbox
  oms_refund_api_rearrangement_topic: oms_refund_api_rearrangement_qa
  loggingTopicSub: inventory_logging_qa-sub
  orderSuccessTopicSub: order-sms-topic_qa-sub
  shipmentUpdateTopic: shipment_update_navik_qa
  shipmentUpdateTopicSub: shipment_update_navik_qa-sub
  returnShipmentUpdateTopic: return_shipment_update_navik_qa
  returnShipmentUpdateTopicSub: return_shipment_update_navik_qa-sub
  refundSmsTriggerTopicSub: refund_sms_trigger_topic_qa-sub
  queueBasedRefundDropoff: queue_based_refund_dropoff_qa
  ots_base_url: https://ordertracking-qa.stylifashion.com
  order_track_history_topic: order_track_history_qa
  seller_central_order_topic: seller-central-create-order-qa
