omsnode:
  domain: oms-api-dev.stylishop.store
  node_env: development
  replicaCount: 1
  appname: omsnode
  mongo_auth_dev: oms
  mongo_url: mongodb://10.128.0.55:27017,10.128.0.56:27017,10.128.0.57:27017
  mongo_db: oms
  mongo_user: oms_app
  mongo_pass: hjbfe6573b4r87fb
  mongo_node_count: 3
  gcp_project_id: stylishopdev
  gs_bucket_name: oms_styli_dev
  consul_host: consul-consul-consul-server.consul
  consul_port: 8500
  consul_credentials_env: credentials_live
  consul_app_config_env: appconfig
  java_order_base_url: http://order-service.oms-dev:8080
  java_customer_base_url: http://customer-service.customer-dev:8080
  python_base_url: http://facto.stylishop.store
  quote_base_url: http://quote-service.quote-dev
  bucket_base_url: https://dev-bucket.stylifashion.com/dev
  elastic_apm_service_name: oms-oms-node-service
  elastic_apm_service_token:
  elastic_apm_service_url: https://10.128.0.50:8200
  apmkey: 4d45uzw9n5208tX9aYBtJ1Zz
  kafka_groupid: oms-service-logging-dev
  kafka_inventory_groupid: inventory-logging-dev
  kafka_clientid: oms-service-consumer-dev
  kafka_brokerlist: 34.72.148.227:9094
  kafka_v2_brokerlist: 34.72.148.227:9094
  kafka_order_success_topic: order-sms-topic_dev
  kafka_inventory_logging_topic: inventory_logging_dev
  kafka_auto_refund_topic: queue_based_refund_dropoff
  kafka_shipment_update_topic: shipment_update_navik_dev
  #   mysql_host: 34.123.21.217
  #   mysql_user: java_test
  #   mysql_pwd: b34ug78cg43i8h98
  #   mysql_db: styli_storefront_test
  #   mysql_port: 3306
  mysql_host: 10.128.0.20
  mysql_user: oms_dev
  mysql_pwd: Jd3b36fvd3guve87
  mysql_db: oms_dev
  mysql_port: 3306
  mulin_url: https://mulin-dev.stylifashion.com
  oms_api_host: https://oms-api-dev.stylishop.store
  braze_base_url: https://rest.fra-01.braze.eu
  braze_auth_token: 647b102f-8c5e-479a-af02-1b9fa83dd3d9
  inventory_base_url: https://inventoryapi-dev.stylishop.store
  custmgmt_base_url: https://customermg-dev.stylishop.store
  eas_url: https://dev-eas.stylifashion.com
  memorylim: 1000Mi
  cpulim: 1000m
  memoryreq: 1000Mi
  cpureq: 1000m
  fresh_chat_whatsapp: https://api.freshchat.com/v2/outbound-messages/whatsapp
  authservice_base_url: https://dev-sentinel-api.stylifashion.com/api/v1/auth
  city_data_api_url: https://adrsmpr-qa.stylishop.store/api/address/city/etd
  main_website_host_name: https://stylishop.com
  kafka_shipment_return_update_topic: return_shipment_update_navik_dev
  return_invoice_bucket_url: navik-sandbox
  kafka_shipment_return_update_topic: return_shipment_update_navik_dev-sub
  order_track_history_topic: order_track_history_dev
