omsnode:
  domain: in-oms-api-uat.stylishop.store
  node_env: uat
  replicaCount: 1
  appname: omsnode
  mongo_node_count: 3
  gcp_project_id: stylishopdev
  gs_bucket_name: oms_styli_dev
  consul_host: consul-consul-server.india-consul
  consul_port: 8500
  consul_credentials_env: credentials_qa
  consul_app_config_env: appConfig_uat
  java_order_base_url: http://order-service-oms.in-oms-uat
  java_customer_base_url: http://customer-service-oms.in-customer-uat
  quote_base_url: http://quote-service.in-quote-uat
  python_base_url: http://facto.stylishop.store
  bucket_base_url: https://in-uat-bucket.stylifashion.com/qa01
  elastic_apm_service_name: in-oms-uat-node-service
  elastic_apm_service_token:
  elastic_apm_service_url: https://10.128.0.50:8200
  apmkey: 4d45uzw9n5208tX9aYBtJ1Zz
  kafka_groupid: in-oms-service-logging-uat
  kafka_inventory_groupid: inventory-logging-uat
  kafka_clientid: oms-service-consumer-uat
  kafka_brokerlist:  kafka-in-kafka-dev-headless.in-kafka-dev:9092
  kafka_v2_brokerlist:  kafka-in-kafka-dev-headless.in-kafka-dev:9092
  kafka_order_success_topic: order-sms-topic_qa01
  kafka_inventory_logging_topic: inventory_logging_uat
  kafka_shipment_update_topic: shipment_update_navik_uat
  mulin_url: https://in-mulin-uat.stylifashion.com
  oms_api_host: https://in-oms-api-uat.stylishop.store
  braze_base_url: https://rest.fra-01.braze.eu
  braze_auth_token: 647b102f-8c5e-479a-af02-1b9fa83dd3d9
  inventory_base_url: http://inventory.in-oms-uat:8080
  eas_url: https://uat-eas.stylifashion.com
  custmgmt_base_url: http://customermg.in-customer-uat:5003
  region: 'IN'
  memorylim: 1000Mi
  cpulim: 700m
  memoryreq: 500Mi
  cpureq: 500m
  archive_mysql_db: in_oms_archive_uat
  authservice_base_url: https://dev-sentinel-api.stylifashion.com/api/v1/auth
  city_data_api_url: http://adrsmpr.adrsmpr-uat:8080
  main_website_host_name: https://uat.stylifashion.com
  kafka_shipment_return_update_topic: return_shipment_update_navik_uat
  oms_refund_api_rearrangement_topic: oms_refund_api_rearrangement_uat
  oms_refund_api_rearrangement_subscription: oms_refund_api_rearrangement_uat-sub
  ots_base_url: https://ordertracking-uat.stylifashion.com
  seller_central_order_topic: seller-central-create-order-uat