quote:
  domain: in-dev-api.stylifashion.com
  replicaCountFront: 2
  replicaCountBack: 1
  styli_env: dev
  debug_params: couchnode:lcb:error,couchnode:lcb:warn node styli_quote_service
  jwt_secret: notToShareQWER
  cb_bucket: in-quote-dev
  cb_address_bucket: india_adrsmpr_dev
  cb_customer_bucket: in_customer_dev
  cb_expiry: 1296000
  cb_kv_timeout: 100
  cb_n1ql_timeout: 1000
  elastic_url: http://search-vm.in-curofy-dev01:8080
  order_count_url: http://order-service.in-oms-dev:8080/rest/order/auth/total/count
  inv_check_url: http://inventory.in-oms-dev:8080/api/inventory/storefront/atp
  order_list_url: http://omsnode.in-oms-dev:8080/v1/orders/list/lifetime
  store_credit_url: http://order-service.in-oms-dev:8080/rest/order/auth/v2/storecredit
  customer_get_profile_url: http://customer-service.in-customer-dev/rest/customer/oms/details
  customer_delete_status_update_url: http://customer-service.in-customer-dev:8080/rest/customer/delete/status/update
  promo_url: http://promoweb.in-promodev:8080
  apigee_base_url: https://apigee-test.stylifashion.com/search-vm-qa
  mysql_host: 35.209.78.189
  mysql_user: oms_dev
  mysql_pass: Jd3b36fvd3guve87
  mysql_dbname: oms_dev
  mysql_port: 3306
  mysql_import_batch_size: 10000
  import_last_updated_after: 2020-10-21 19:12:55
  consul_host: consul-consul-server.india-consul
  consul_port: 8500
  consul_key: appConfig_dev
  consul_promo_base_url: promoBaseUrl
  consul_addressMapper_sa_dev: addressMapper_sa_dev
  consul_addressMapper_ae_dev: addressMapper_ae_dev
  consul_addressMapper_kw_dev: addressMapper_kw_dev
  consul_addressMapper_bh_dev: addressMapper_bh_dev
  consul_addressMapper_qa_dev: addressMapper_qa_dev
  gcp_addressMapper_in_dev: addressMapper_in_dev
  consul_customer_auth_config: java/customer-service/authorization_dev
  consul_promo_keys: promo/promo
  kafka_brokers: 34.72.148.227:9092:9092
  kafka_client_id: quote-dev-server
  kafka_topic_quote: quote_dev
  kafka_topic_delete_customer: deleted_customers_dev
  kafka_topic_quote_items: quoteItem_dev
  kafka_group_id: consumer-quote-dev
  new_relic_env: Node-Quote_Service-Dev
  elastic_apm_service_name: in-dev-quote-service
  elastic_apm_service_token:
  elastic_apm_service_url: http://falcondev851-apm-server.default:8200
  fetch_city_endpoint: http://adrsmpr.in-adrsmpr-dev:8080/api/address/search/city
  consul_payment_methods: payment_methods_dev
  eas_url: https://dev-eas.stylifashion.com
  region: IN
  gcp_bucket_url: https://in-dev-bucket.stylifashion.com
  consul_tax: tax/in_tax_dev
  redis_url: redis://10.190.197.91:6379
  memorylim: 1200Mi
  cpulim: 700m
  memoryreq: 1200Mi
  cpureq: 700m
  payment_service_url: http://payment.in-payment-dev:5001
  kafka_price_drop_topic: collect-price-drop-dev
  braze_base_url: https://rest.fra-01.braze.eu/users/track
  braze_auth_token: 647b102f-8c5e-479a-af02-1b9fa83dd3d9
  kafka_mulin_client_id: nodeJS-mulin-server-secondary
