quote:
  domain: in-qa-api.stylifashion.com
  replicaCountFront: 2
  replicaCountBack: 1
  styli_env: qa
  debug_params: couchnode:lcb:error,couchnode:lcb:warn node styli_quote_service
  jwt_secret: notToShareQWER
  cb_address: couchbase://10.128.0.19,10.128.0.95,10.128.0.117
  cb_bucket: in-quote-qa
  cb_pass: lsdhcvdwhjvcjevcj
  cb_bucket: quote
  cb_address_bucket: in_adrsmpr_qa
  cb_customer_bucket: in_customer_qa
  cb_expiry: 1296000
  cb_kv_timeout: 3000
  cb_n1ql_timeout: 5000
  elastic_url: http://search-vm.in-curofy-qa:8080
  order_count_url: http://order-service.in-oms-qa/rest/order/auth/total/count
  inv_check_url: http://inventory.in-oms-qa:8080/api/inventory/storefront/atp
  store_credit_url: http://order-service.in-oms-qa/rest/order/auth/v2/storecredit
  customer_get_profile_url: http://customer-service-oms.in-customer-qa/rest/customer/oms/details
  customer_delete_status_update_url: http://customer-service.in-oms-qa/rest/customer/delete/status/update
  order_list_url: http://omsnode.in-oms-qa:8080/v1/orders/list/lifetime
  promo_url: http://promoweb.in-qa
  apigee_base_url: https://apigee-test.stylifashion.com/search-vm-qa
  mysql_host: 10.128.0.25
  mysql_user: magento
  mysql_pass: 2eyXtXHV7L
  mysql_dbname: styli_storefront_prod
  mysql_port: 3306
  mysql_import_batch_size: 10000
  import_last_updated_after: 2020-10-21 19:12:55
  consul_host: consul-consul-server.india-consul
  consul_port: 8500
  consul_key: appConfig_qa
  consul_promo_base_url: promoBaseUrl
  consul_addressMapper_sa_qa: addressMapper_sa_qa
  consul_addressMapper_ae_qa: addressMapper_ae_qa
  consul_addressMapper_kw_qa: addressMapper_kw_qa
  consul_addressMapper_bh_qa: addressMapper_bh_qa
  consul_addressMapper_qa_qa: addressMapper_qa_qa
  consul_addressMapper_om_qa: addressMapper_om_qa
  consul_customer_auth_config: java/customer-service/authorization_qa
  consul_promo_keys: promo/promo
  kafka_brokers: 34.72.148.227:9092:9092
  kafka_client_id: quote-qa-server
  kafka_topic_quote: quote
  kafka_topic_quote_items: quoteItem
  kafka_topic_delete_customer: deleted_customers_qa
  kafka_group_id: consumer-quote-qa
  new_relic_env: Node-Quote_Service-QA
  elastic_apm_service_name: in-qa-quote-service
  elastic_apm_service_token:
  elastic_apm_service_url: http://falcondev851-apm-server.default:8200
  fetch_city_endpoint: http://adrsmpr.in-adrsmpr-qa:8080/api/address/search/city
  consul_payment_methods: payment_methods_qa
  eas_url: https://qa-eas.stylifashion.com
  region: 'IN'
  consul_tax: tax/in_tax_qa
  memorylim: 700Mi
  cpulim: 500m
  memoryreq: 500Mi
  cpureq: 300m
  payment_service_url: http://payment.in-payment-qa:5001
  redis_url: redis://10.190.197.91:6379
  kafka_price_drop_topic: collect-price-drop-qa
  braze_base_url: https://rest.fra-01.braze.eu/users/track
  braze_auth_token: 647b102f-8c5e-479a-af02-1b9fa83dd3d9
  kafka_mulin_client_id: nodeJS-mulin-server-secondary
