quote:
  domain: uat-api.stylifashion.com
  replicaCountFront: 2
  replicaCountBack: 1
  styli_env: qa01
  apmkey: 4d45uzw9n5208tX9aYBtJ1Zz
  debug_params: couchnode:lcb:error,couchnode:lcb:warn node styli_quote_service
  cb_address: couchbase://10.128.0.61,10.128.0.62,10.128.0.63
  cb_user: quote_uat
  cb_pass: j454hj67vbh56h
  cb_bucket: quote_uat
  cb_address_bucket: adrsmpr_uat
  cb_customer_bucket: customer
  cb_expiry: 1296000
  cb_kv_timeout: 100
  cb_n1ql_timeout: 1000
  elastic_url: http://search-vm.qa01:8080
  order_count_url: http://order-service/rest/order/auth/total/count
  inv_check_url: https://inventoryapi-uat.stylifashion.com/api/inventory/storefront/atp
  order_list_url: http://omsnode.oms-uat:8080/v1/orders/list/lifetime
  store_credit_url: http://order-service/rest/order/auth/v2/storecredit
  customer_delete_status_update_url: http://customer-service.customer-uat/rest/customer/delete/status/update
  customer_get_profile_url: http://customer-service.customer-uat/rest/customer/oms/details
  promo_url: http://promoweb.qa01
  apigee_base_url: https://apigee-test.stylifashion.com/search-vm-qa
  mysql_host: 10.128.0.20
  mysql_user: oms_uat
  mysql_pass: Vehufb38fbhjfe84
  mysql_dbname: oms_uat
  mysql_port: 3306
  mysql_import_batch_size: 10000
  import_last_updated_after: 2020-10-21 19:12:55
  consul_host: consul-consul-consul-server.consul
  consul_port: 8500
  consul_key: appConfig_qa01
  consul_promo_base_url: promoBaseUrl
  consul_addressMapper_sa_qa: addressMapper_sa_qa01
  consul_addressMapper_ae_qa: addressMapper_ae_qa01
  consul_addressMapper_kw_qa: addressMapper_kw_qa01
  consul_addressMapper_bh_qa: addressMapper_bh_qa01
  consul_addressMapper_qa_qa: addressMapper_qa_qa01
  consul_addressMapper_om_qa: addressMapper_om_qa01
  consul_customer_auth_config: java/customer-service/authorization_qa01
  consul_promo_keys: promo/promo
  kafka_brokers: 34.72.148.227:9092:9092
  kafka_client_id: quote-uat-server
  kafka_topic_quote: quote_uat
  kafka_topic_quote_items: quoteItem_uat
  kafka_group_id: consumer-quote-uat
  kafka_store_credit_topic: customer_store_credit_uat
  kafka_topic_delete_customer: deleted_customers_uat
  new_relic_env: Node-Quote_Service-QA01
  elastic_apm_service_name: qa01-quote-service
  elastic_apm_service_token:
  elastic_apm_service_url: https://10.128.0.50:8200
  fetch_city_endpoint: http://adrsmpr.adrsmpr-uat:8080/api/address/search/city
  consul_payment_methods: payment_methods_qa01
  eas_url: https://uat-eas.stylifashion.com
  region: 'GULF'
  memorylim: 1200Mi
  cpulim: 700m
  memoryreq: 1200Mi
  cpureq: 700m
  payment_service_url: http://payment.qa01:5001
  kafka_price_drop_topic: collect-price-drop-uat
  braze_base_url: https://rest.fra-01.braze.eu/users/track
  braze_auth_token: 647b102f-8c5e-479a-af02-1b9fa83dd3d9
  kafka_mulin_client_id: nodeJS-mulin-server-uat
  redis_url: redis://10.190.197.91:6379
  customer_update_wishlist_url: http://customer-service.customer-uat/rest/customer/auth/v4.1/wishlist
  servicekeyname: quote-uat