quote:
  domain: dev-api.stylifashion.com
  replicaCountFront: 2
  replicaCountBack: 1
  styli_env: dev
  debug_params: couchnode:lcb:error,couchnode:lcb:warn node styli_quote_service
  cb_address_bucket: adrsmpr_dev
  cb_customer_bucket: customer_dev
  cb_expiry: 1296000
  cb_kv_timeout: 100
  cb_n1ql_timeout: 1000
  elastic_url: http://search-vm.dev01:8080
  order_count_url: http://order-service.oms-dev:8080/rest/order/auth/total/count
  inv_check_url: http://inventory.oms-dev:8080/api/inventory/storefront/atp
  order_list_url: http://omsnode.oms-dev:8080/v1/orders/list/lifetime
  store_credit_url: http://order-service.oms-dev/rest/order/auth/v2/storecredit
  customer_delete_status_update_url: http://customer-service.customer-dev/rest/customer/delete/status/update
  customer_get_profile_url: http://customer-service.customer-dev/rest/customer/oms/details
  promo_url: http://promoweb.promodev
  apigee_base_url: https://apigee-test.stylifashion.com/search-vm-qa
  mysql_host: 35.209.78.189
  mysql_user: oms_dev
  mysql_pass: Jd3b36fvd3guve87
  mysql_dbname: oms_dev
  mysql_port: 3306
  mysql_import_batch_size: 10000
  import_last_updated_after: 2020-10-21 19:12:55
  consul_host: consul-consul-consul-server.consul
  consul_port: 8500
  consul_key: appConfig_dev
  consul_promo_base_url: promoBaseUrl
  consul_addressMapper_sa_qa: addressMapper_sa_dev
  consul_addressMapper_ae_qa: addressMapper_ae_dev
  consul_addressMapper_kw_qa: addressMapper_kw_dev
  consul_addressMapper_bh_qa: addressMapper_bh_dev
  consul_addressMapper_qa_qa: addressMapper_qa_dev
  consul_addressMapper_om_qa: addressMapper_om_dev
  consul_customer_auth_config: java/customer-service/authorization_dev
  consul_promo_keys: promo/promo
  kafka_brokers: 34.72.148.227:9092:9092
  kafka_client_id: quote-dev-server
  kafka_topic_quote: quote_dev
  kafka_topic_delete_customer: deleted_customers_dev
  kafka_topic_quote_items: quoteItem_dev
  kafka_group_id: consumer-quote-dev
  new_relic_env: Node-Quote_Service-Dev
  elastic_apm_service_name: dev-quote-service
  elastic_apm_service_token:
  elastic_apm_service_url: https://10.128.0.50:8200
  apmkey: 4d45uzw9n5208tX9aYBtJ1Zz
  fetch_city_endpoint: http://adrsmpr.adrsmpr-dev:8080/api/address/search/city
  consul_payment_methods: payment_methods_dev
  eas_url: https://dev-eas.stylifashion.com
  region: 'GULF'
  redis_url: redis://10.190.197.91:6379
  memorylim: 1200Mi
  cpulim: 700m
  memoryreq: 1200Mi
  cpureq: 700m
  payment_service_url: http://payment.dev:5001
  kafka_price_drop_topic: collect-price-drop-dev
  braze_base_url: https://rest.fra-01.braze.eu/users/track
  braze_auth_token: 647b102f-8c5e-479a-af02-1b9fa83dd3d9
  kafka_mulin_client_id: nodeJS-mulin-server-dev
  customer_update_wishlist_url: http://customer-service.customer-dev/rest/customer/auth/v4.1/wishlist
  deleteCustomersSub: deleted_customers_dev-sub
  priceDropSub: collect-price-drop_dev-sub
  servicekeyname: quote-dev
