quote:
  domain: prod-api.stylishop.com
  replicaCountFront: 2
  replicaCountBack: 5
  styli_env: live
  debug_params: couchnode:lcb:error,couchnode:lcb:warn node styli_quote_service
  cb_address_bucket: adrsmpr
  cb_customer_bucket: customermg
  cb_expiry: 1296000
  cb_kv_timeout: 3000
  cb_n1ql_timeout: 5000
  elastic_url: http://search-vm.elasticprod:8080
  order_count_url: http://order-service.oms-prod/rest/order/auth/total/count
  inv_check_url: http://inventory.oms-prod:8080/api/inventory/storefront/atp
  order_list_url: http://omsnode.oms-prod:8080/v1/orders/list/lifetime
  store_credit_url: http://order-service.oms-prod/rest/order/auth/v2/storecredit
  customer_delete_status_update_url: http://customer-service.customer-prod/rest/customer/delete/status/update
  customer_get_profile_url: http://customer-service.customer-prod/rest/customer/oms/details
  promo_url: http://promoweb.promoprod
  apigee_base_url: https://api.stylishop.com/search-vm-prod
  mysql_host: 10.154.0.31
  mysql_user: quote
  mysql_pass: bcjewb23e!!de2idf32
  mysql_dbname: styli_storefront_prod
  mysql_port: 3306
  mysql_import_batch_size: 10000
  import_last_updated_after: 2020-10-26 02:45:00
  consul_host: consul-consul-server.default
  consul_port: 8500
  consul_key: appConfig_live
  consul_promo_base_url: promoBaseUrl
  consul_addressMapper_sa_qa: addressMapper_sa_live
  consul_addressMapper_ae_qa: addressMapper_ae_live
  consul_addressMapper_kw_qa: addressMapper_kw_live
  consul_addressMapper_bh_qa: addressMapper_bh_live
  consul_addressMapper_qa_qa: addressMapper_qa_live
  consul_addressMapper_om_qa: addressMapper_om_live
  consul_customer_auth_config: java/customer-service/authorization_live
  consul_promo_keys: promo/promo
  kafka_brokers: 10.154.0.30:9092
  kafka_client_id: quote-prod-server
  kafka_topic_quote: quote
  kafka_topic_quote_items: quoteItem
  kafka_topic_delete_customer: deleted_customers_live
  kafka_group_id: consumer-quote
  new_relic_env: Node-Quote_Service-LIVE
  elastic_apm_service_name: quote-service
  elastic_apm_service_token:
  elastic_apm_service_url: https://10.154.0.54:8200
  apmkey: 8667g6b5cxFJj6GW8c5NxH5M
  consul_payment_methods: payment_methods_live
  fetch_city_endpoint: http://adrsmpr.adrsmpr-prod:8080/api/address/search/city
  eas_url: http://eas.easprod:8080
  region: 'GULF'
  memorylim: 2000Mi
  cpulim: 2000m
  memoryreq: 2000Mi
  cpureq: 2000m
  payment_service_url: http://payment.payment-prod:5001
  kafka_price_drop_topic: collect-price-drop-prod
  braze_base_url: https://rest.fra-01.braze.eu/users/track
  braze_auth_token: eca0661e-90b6-4fdd-aa86-8bef847e4e35
  kafka_mulin_client_id: nodeJS-mulin-server
  redis_url: redis://10.118.128.20:6379
  customer_update_wishlist_url: http://customer-service.customer-prod/rest/customer/auth/v4.1/wishlist
  deleteCustomersSub: deleted_customers_prod-sub
  priceDropSub: collect-price-drop_prod-sub
  servicekeyname: quote-prod
