quote:
  domain: in-uat-api.stylifashion.com
  replicaCountFront: 2
  replicaCountBack: 1
  styli_env: qa01
  debug_params: couchnode:lcb:error,couchnode:lcb:warn node styli_quote_service
  jwt_secret: notToShareQWER
  cb_address_bucket: in_adrsmpr_uat
  cb_customer_bucket: in_customer_uat
  cb_expiry: 1296000
  cb_kv_timeout: 100
  cb_n1ql_timeout: 1000
  elastic_url: http://search-vm.in-curofy-uat:8080
  order_count_url: http://order-service.in-oms-uat/rest/order/auth/total/count
  order_list_url: http://omsnode.in-oms-uat:8080/v1/orders/list/lifetime
  inv_check_url: http://inventory.in-oms-uat:8080/api/inventory/storefront/atp
  store_credit_url: http://order-service.in-oms-uat/rest/order/auth/v2/storecredit
  customer_get_profile_url: http://customer-service-oms.in-customer-uat/rest/customer/oms/details
  customer_delete_status_update_url: http://customer-service.in-customer-uat/rest/customer/delete/status/update
  promo_url: http://promoweb.in-promo-uat
  apigee_base_url: https://apigee-test.stylifashion.com/search-vm-qa
  mysql_import_batch_size: 10000
  import_last_updated_after: 2020-10-21 19:12:55
  consul_host: consul-consul-server.india-consul
  consul_port: 8500
  consul_key: appConfig_qa01
  consul_promo_base_url: promoBaseUrl
  consul_addressMapper_sa_qa: addressMapper_sa_qa01
  consul_addressMapper_ae_qa: addressMapper_ae_qa01
  consul_addressMapper_kw_qa: addressMapper_kw_qa01
  consul_addressMapper_bh_qa: addressMapper_bh_qa01
  consul_addressMapper_qa_qa: addressMapper_qa_qa01
  consul_addressMapper_om_qa: addressMapper_om_qa01
  consul_customer_auth_config: java/customer-service/authorization_qa01
  consul_promo_keys: promo/promo
  kafka_brokers: kafka-in-kafka-dev-headless.in-kafka-dev:9092
  kafka_client_id: in-quote-uat-server
  kafka_topic_quote: in-quote_uat
  kafka_topic_quote_items: in-quoteItem_uat
  kafka_group_id: in-consumer-quote-uat
  kafka_store_credit_topic: in_customer_store_credit_uat
  kafka_topic_delete_customer: in_deleted_customers_uat
  new_relic_env: Node-Quote_Service-QA01
  elastic_apm_service_name: in-uat-quote-service
  elastic_apm_service_token:
  elastic_apm_service_url: http://falcondev851-apm-server.default:8200
  fetch_city_endpoint: http://adrsmpr.in-adrsmpr-uat:8080/api/address/search/city
  consul_payment_methods: payment_methods_qa01
  eas_url: https://uat-eas.stylifashion.com
  region: 'IN'
  consul_tax: tax/in_tax_qa01
  memorylim: 700Mi
  cpulim: 500m
  memoryreq: 500Mi
  cpureq: 300m
  redis_url: redis://10.190.197.91:6379
  payment_service_url: http://payment.in-payment-uat:5001
  kafka_price_drop_topic: collect-price-drop-uat
  braze_base_url: https://rest.fra-01.braze.eu/users/track
  braze_auth_token: 647b102f-8c5e-479a-af02-1b9fa83dd3d9
  kafka_mulin_client_id: nodeJS-mulin-server-uat
