payment:
  domain: in-payment.stylishop.com
  replicaCount: 2
  appname: payment
  node_env: 'production'
  host: '0.0.0.0'
  port: 5001
  consul_host: india-consul-consul-server.in-consul
  consul_port: 8500
  consul_key: appConfig
  consul_payment_methods: payment_methods_live
  debug_params: couchnode:lcb:error,couchnode:lcb:warn node customer_management_service
  redis_port: 6379
  redis_host: 10.118.128.3
  merchant_key_path: /var/gcppath/merchant_id.key.pem
  merchant_cert_path: /var/gcppath/merchant_id.crt.pem
  elastic_apm_service_name: in-payment-service
  elastic_apm_service_url: https://10.154.0.54:8200 
  memorylim: 1000Mi
  cpulim: 500m
  memoryreq: 1000Mi
  cpureq: 500m
