steps:

  - id: 'report-dir-for-parralel-build'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - -c
      - |
        mkdir dockerfilescan
        mkdir dockerimagescan

  - name: 'gcr.io/kaniko-project/executor:latest'
    id: build
    args:
    - --destination=$_CLOUDSDK_COMPUTE_ZONE-docker.pkg.dev/$PROJECT_ID/stylidev-sentinel/styli-sentinel:$REVISION_ID
    - --cache=true
    - --cache-ttl=1000h
    - --context=backend

  - name: 'node:20.14.0'
    entrypoint: 'bash'
    id: yarn-install
    dir: backend
    args:
      - '-c'
      - |
        if [[ "$_SEC_OPS_" == "true" ]]; then
          yarn install
        else
          echo "Skipping yarn install"
        fi

  - id: 'owasp-pre-requisites'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    volumes:
    - name: 'code'
      path: /code  
    args: 
      - -c
      - |
        if [[ "$_SEC_OPS_" == "true" ]]; then
         mkdir data
         mkdir report
         gsutil -m cp -r gs://styli_cache/data ./data
         chmod -R 777 data
         chmod -R 777 report
         ls -la
         pwd
         ls -la backend/
         cp -rf backend/* /code/
        fi
  
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    volumes:
    - name: 'code'
      path: /code
    args: 
      - -c
      - |
        if [[ "$_SEC_OPS_" == "true" ]]; then
          docker run --rm -v /workspace/data/data:/usr/share/dependency-check/data:rw -v /workspace/backend:/project:rw -v /workspace/report:/usr/share/report docker.io/owasp/dependency-check:8.4.3 dependency-check.sh  --scan /project/ -f CSV -o /usr/share/report --disableYarnAudit
        fi
        
  - name: 'gcr.io/cloud-builders/git'
    id: ci-report-dir
    entrypoint: 'bash'
    args: 
      - -c
      - |
        mkdir /report/$REVISION_ID
    volumes:
      - name: 'report'
        path: '/report'
        
  - name: 'aquasec/trivy:0.36.1'
    id: 'Dockerfile scan'
    dir: backend
    args: ['config', './Dockerfile', '-f', 'json', '-o', '/report/$REVISION_ID/trivy_docker_scan_report.txt']
    volumes:
    - name: 'report'
      path: '/report'
 

  - name: 'aquasec/trivy:0.36.1'
    id: 'Docker image scan'
    dir: backend
    args: ['image', '-f', 'json' ,'-o', '/report/$REVISION_ID/trivy_docker_image_scan_report.txt', '$_CLOUDSDK_COMPUTE_ZONE-docker.pkg.dev/$PROJECT_ID/stylidev-sentinel/styli-sentinel:$REVISION_ID']
    volumes:
    - name: 'report'
      path: '/report' 

  - name: 'gcr.io/cloud-builders/git'
    id: ci-status-generate
    entrypoint: 'bash'
    volumes:
      - name: 'report'
        path: '/report'
    args:
    - -c
    - |
      cp /workspace/backend/report/dependency-check-report.csv /report/$REVISION_ID/
      mkdir failurereports
      matching_files=()
      for filename in /report/$REVISION_ID/*; do
          content=$(cat "$filename")
          if echo "$content" | grep -q "${_CRITICALITY}"; then
              matching_files+=("$filename")
              cp $filename failurereports/
         fi
      done
      if [ ${#matching_files[@]} -gt 0 ]; then
          echo "Found security risks in the reports: ${matching_files[@]}"
      fi
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '/report/*', 'gs://$PROJECT_ID-cireports/']
    volumes:
    - name: 'report'
      path: '/report'

  - id: ci-status-gate-check
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    volumes:
    - name: 'report'
      path: '/report'
    args:
    - -c
    - |
      if [ "$(ls -A failurereports)" ]; then
        # Check for security risks in the reports
        matching_files=()
        for filename in /report/failurereports/*; do
          content=$(cat "$filename")
          if echo "$content" | grep -q "${_CRITICALITY}"; then
            matching_files+=("$filename")
          fi
        done

        if [ ${#matching_files[@]} -gt 0 ]; then
          echo "SECURITY RISK FOUND AND HENCE FAILING THE PIPELINE. PLEASE CHECK THE REPORTS AT https://console.cloud.google.com/storage/browser/$PROJECT_ID-cireports/report/$REVISION_ID. THE FOLLOWING FILES NEED TO BE CHECKED:"
          ls -l "${matching_files[@]}"
          ls -l
          docker run -i --rm -v /workspace/failurereports:/app/failurereports -e TO_EMAIL=${_TO_EMAIL} -e FROM_EMAIL=sre@stylishop.com -e SUBJECT="$TRIGGER_NAME CI Status" -e TEXT="PFA" -e ATTACHMENT_DIR=failurereports/ gcr.io/$PROJECT_ID/sendgrid-client
        else
          echo "NO SECURITY RISKS FOUND AND HENCE PROCEEDING TO NEXT STEP"
        fi
      else
        echo "No files found in failurereports directory. Proceeding to the next step."
      fi

  - name: 'gcr.io/cloud-builders/git'
    id: helm-lint-setup
    waitFor: ['-']
    entrypoint: 'bash'
    dir: 'backend'
    args:
    - -c
    - |
      cp -r .helm sentinel
      
  - id: ‘helm lint’
    waitFor: ['helm-lint-setup']
    name: 'gcr.io/$PROJECT_ID/helm'
    dir: 'backend'
    env:
     - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
     - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
     - 'KUBECONFIG=/kube/config'
    args: [ 
     'lint', '--namespace', '$_STYLI_ENV', '-f', '.helm/values.$_STYLI_ENV.yaml',
      '--set', 'sentinel.image=$_CLOUDSDK_COMPUTE_ZONE-docker.pkg.dev/$PROJECT_ID/stylidev-sentinel/styli-sentinel:$REVISION_ID',
      'sentinel'
    ]


   ### Deploy
  - id: 'helm-deploy'
    name: 'gcr.io/$PROJECT_ID/helm'
    dir: 'backend'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    args: [
      'upgrade', '--install',  '--force', 'styli-sentinel-$_STYLI_ENV',
      '--namespace', '$_STYLI_ENV', '-f', '.helm/values.$_STYLI_ENV.yaml',
      '--set', 'sentinel.image=$_CLOUDSDK_COMPUTE_ZONE-docker.pkg.dev/$PROJECT_ID/stylidev-sentinel/styli-sentinel:$REVISION_ID',
      'sentinel'
    ]

  
  

timeout: 1800s
