const express = require('express');
const authRoute = require('./auth.route');
// const userRoute = require('./user.route');
const docsRoute = require('./docs.route');
const healthRoute = require('./health.route');
// const productsRoute = require('./products.route');
// const activityController = require('./activity.route');
const rolesRoute = require('./roles.route');
const dashboardRoute = require('./dashboard.route');
const misc = require('./misc.route');
const order = require('./order.route');
const customer = require('./customer.route');
const rest = require('./rest.route');
const rma = require('./rma.route');
const logging = require('./logging.route');
const store = require('./store.route');
const config = require('./config.route');
const alerts = require('./alerts.route');
const smsRoutes = require('./sms.route');
const bankTransfersRoute = require('./bank.route');
const earn = require('./earn.route');
const archiveDBSync = require('./archive.route');
const sellerRoute = require('./seller.route');
const router = express.Router();

// router.use('/users', userRoute);
router.use('/auth', authRoute);
router.use('/docs', docsRoute);
router.use('/health', healthRoute);
// router.use('/products', productsRoute);
// router.use('/activity', activityController);
router.use('/roles', rolesRoute);
router.use('/dashboard', dashboardRoute);
router.use('/misc', misc);
router.use('/orders', order);
router.use('/customers', customer);
router.use('/rest', rest);
router.use('/alert', alerts);
router.use('/banktransfer', bankTransfersRoute);
router.use('/rma', rma);
router.use('/logging', logging);
router.use('/store', store);
router.use('/config', config);
router.use('/sms', smsRoutes);
router.use('/earn', earn);
router.use('/archive', archiveDBSync);
router.use('/seller', sellerRoute);

module.exports = router;
